import{fetchData as e,langSelection as i}from"./api.js";export function carregarConteudoSobre(){e(i()).then(e=>{let i=e.find(e=>"geral"===e.id);document.getElementById("foto").innerHTML=`<img src=${i.fotoperfil} alt="foto" Loading="lazy">`,document.getElementById("nome").innerHTML=`<h2>${i.nome}</h2><h1>${i.sobrenome}</h1>`,document.getElementById("cargo").innerHTML=`<h3>${i.cargo}</h3>`,document.getElementById("datanasc").innerHTML=`<img src="../images/birthday.svg" alt="" loading="lazy"><p>${i.datanascimento}</p>`,document.getElementById("telefone").innerHTML=`<img src="../images/telephone.svg" alt="" loading="lazy"><p>${i.telefone}</p>`,document.getElementById("email").innerHTML=`<img src="../images/email.svg" alt="" loading="lazy"><p>${i.email}</p>`,document.getElementById("endereco").innerHTML=`<img src="../images/address.svg" alt="" loading="lazy"><p>${i.endereco}</p>`;let t=e.find(e=>"sobremim"===e.id);document.getElementById("head-title").innerHTML=`${t.titulo} - Gabriel G.F.`,document.getElementById("titulosobre").innerHTML=`<h2>${t.titulo}</h2>`,document.getElementById("conteudo").innerHTML=`<p>${t.descricao}</p>`;let l=e.find(e=>"formacao"===e.id),n=document.getElementById("timeline");document.getElementById("tituloexp").innerHTML=`<h2>${l.titulo}</h2>`,organizarExp(l).forEach(e=>{let i=document.createElement("li");i.innerHTML=`
                    <div class="content">
                        <h3>${e.cargo}</h3>
                        <p>${e.empresa}</p>
                        <p>${e.data}</p>
                        <p>${e.descricao}</p>
                    </div>
                `,n.appendChild(i)});let a=e.find(e=>"habilidades"===e.id);document.getElementById("tituloskills").innerHTML=`<h2>${a.titulo}</h2>`,document.getElementById("titulohs").innerHTML=`<i>${a.quadros.hardskills}</i>`,document.getElementById("tituloss").innerHTML=`<i>${a.quadros.softskills}</i>`,document.getElementById("tituloidiomas").innerHTML=`<i>${a.quadros.idiomas}</i>`,Object.entries(a).forEach(([e,i])=>{if("id"!==e&&"titulo"!==e&&"quadros"!==e){let t=document.getElementById(`lista${i.categoria}`),l=document.createElement("li");l.classList.add("skill"),l.dataset.level=i.nivel,l.innerHTML=`
                    <h4>${e}</h4>
                    <div class="barra">
                        <div class="segmento"></div>
                        <div class="segmento"></div>
                        <div class="segmento"></div>
                    </div>
                `,t.appendChild(l)}}),classificarSkills()})}function classificarSkills(){let e=document.querySelectorAll(".skill");e.forEach(e=>{let i=e.dataset.level,t=e.querySelectorAll(".segmento");for(let l=0;l<i;l++)t[l].style.backgroundColor="#EBA417"})}function organizarExp(e){let i=[];return Object.entries(e).forEach(([e,t])=>{"id"!==e&&"titulo"!==e&&i.push(t)}),i.sort((e,i)=>parseInt(e.inicio)-parseInt(i.inicio))}